[package]
name = "zed-rhizome"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.1.0"
