name = "Melbi"
grammar = "melbi"
path_suffixes = ["rz", "rhz", "melbi"]
line_comments = ["// "]
autoclose_before = ";:.,=}])>` \n\t"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string"] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
    { start = "`", end = "`", close = true, newline = false, not_in = ["string", "comment"] },
]
tab_size = 4
