[package]
name = "melbi-lsp"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
melbi = { path = "../.." }
tokio.workspace = true
pest.workspace = true
tower-lsp = "0.20.0"
